version: '3.8'

services:
  prueba-jenkins-back:
    build: .
    container_name: container-dfp-backend
    depends_on:
      - elasticsearch
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - test-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - test-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
